# Copyright (c) 2021 Andy Maleh
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
# The DCR Icon is generated by Glimmer GUI DSL code script

require 'glimmer-dsl-swt'
require 'glimmer-cp-stickfigure'

include Glimmer

@font_name = 'Tahoma'
    
@image = image(512, 512) {
  rectangle(0, 0, :max, :max) {
    background rgb(255, 254, 114)
  }
  stick_figure(
        location_x: 80,
        location_y: 30,
        size: 290,
      ) {
    line_width 12
    foreground :black
  }
  text('DCR', :default, [:default, 150]) {
    font name: @font_name, height: 155, style: :bold
  }
}

shell(:no_trim) {
  image @image
  label {
    image @image
  }
}.open
